name: Formula CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  formula:
    runs-on: macos-latest

    steps:
      - name: Check out tap
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10

      - name: Update Homebrew
        run: brew update

      - name: Check formula style
        run: brew style Formula/trustcheck.rb

      - name: Install formula from source
        run: brew install --build-from-source ./Formula/trustcheck.rb

      - name: Run formula test
        run: brew test ./Formula/trustcheck.rb
